### ISSUE TITLE
druidplugin does not support alerting

### ISSUE THREAD

**Issue by HoraceLee** [grafana-druid-plugin/druidplugin#108] opened 2021-01-07 07:52 UTC
druidplugin does not support alerting queries which is a very useful feature.
![image](https://user-images.githubusercontent.com/9915526/103866167-4edeb480-5100-11eb-9130-1be671c00125.png)

**Comment by Gauravshah** [comment] 2021-01-07 09:22
duplicate of https://github.com/grafana-druid-plugin/druidplugin/issues/21

**Closed by Gauravshah** 2021-01-07 09:22 UTC

**Comment by jbguerraz** [comment] 2021-01-08 13:46
@HoraceLee  feel free to take a look on https://github.com/grafana-druid-plugin/druidplugin/issues/107
This new plugin supports alerting.
